# Generated by Django 2.2.9 on 2020-01-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата синхронизации')),
            ],
            options={
                'verbose_name': 'дата синхронизации',
                'verbose_name_plural': 'даты синхронизации',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('reg_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='regNumber')),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='serialNumber')),
                ('garage_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='garageNumber')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='phone')),
                ('sim_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='simNumber')),
                ('fuel_sort', models.CharField(blank=True, max_length=150, null=True, verbose_name='fuelSort')),
                ('brand', models.CharField(blank=True, max_length=150, null=True, verbose_name='brand')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='description')),
                ('group_ids', models.CharField(blank=True, max_length=150, null=True, verbose_name='groupIds')),
                ('nav_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='id')),
                ('sync_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='nav_client.SyncDate', verbose_name='дата синхронизации')),
            ],
            options={
                'verbose_name': 'водитель',
                'verbose_name_plural': 'водители',
            },
        ),
    ]
