# Generated by Django 2.2.10 on 2020-02-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'автомобиль  ', 'verbose_name_plural': 'автомобили'},
        ),
        migrations.AlterModelOptions(
            name='syncdate',
            options={'get_latest_by': 'datetime', 'verbose_name': 'дата синхронизации', 'verbose_name_plural': 'даты синхронизации'},
        ),
        migrations.AddField(
            model_name='flattablerow',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flattablerows', to='nav_client.Device', verbose_name='автомобиль'),
        ),
    ]
