# Generated by Django 2.2.10 on 2020-02-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav_client', '0002_auto_20200221_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'автомобиль', 'verbose_name_plural': 'автомобили'},
        ),
    ]
