# Generated by Django 2.2.10 on 2020-03-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_client', '0003_auto_20200225_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='mt_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='mt_id'),
        ),
    ]
