# Generated by Django 2.2.10 on 2020-03-12 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nav_client', '0004_geozone_mt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncdate',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата синхронизации'),
        ),
    ]
