# Generated by Django 2.2.11 on 2020-03-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_client', '0005_auto_20200311_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGeoZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('points', models.ManyToManyField(to='nav_client.Point', verbose_name='Точки')),
            ],
            options={
                'verbose_name': 'CustomGeoZone',
                'verbose_name_plural': 'CustomGeoZones',
            },
        ),
    ]
