# Generated by Django 2.2.11 on 2020-03-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav_client', '0006_merge_20200313_1307'),
        ('nav_client', '0006_customgeozone'),
    ]

    operations = [
    ]
