# Generated by Django 2.2.12 on 2020-04-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_client', '0008_auto_20200417_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='is_custom',
            field=models.BooleanField(blank=True, null=True, verbose_name='Является кастомной'),
        ),
        migrations.DeleteModel(
            name='CustomGeoZone',
        ),
    ]
