# Generated by Django 2.2.12 on 2020-04-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_client', '0009_auto_20200420_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geozone',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Является кастомной'),
        ),
    ]
