# Generated by Django 2.2.9 on 2020-01-21 01:19

from django.db import migrations, models
import django.db.models.deletion
import route_log.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalExportDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AdditionalExportDocument',
                'verbose_name_plural': 'AdditionalExportDocuments',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=route_log.models.get_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GeoZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='P2Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2documents', to='route_log.Document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'P2Document',
                'verbose_name_plural': 'P2Documents',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReTimeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ReTimeDocument',
                'verbose_name_plural': 'ReTimeDocuments',
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqsdocs', to='route_log.Document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'RequestDocument',
                'verbose_name_plural': 'RequestDocuments',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('additional_export_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='route_log.AdditionalExportDocument', verbose_name='add_ex_do')),
                ('p2document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='route_log.P2Document', verbose_name='p2document')),
                ('re_time_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='route_log.ReTimeDocument', verbose_name='re_time_document')),
                ('request_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='route_log.RequestDocument', verbose_name='request_document')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
