# Generated by Django 2.2.9 on 2020-01-23 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nav_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Отчет', max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='ContainerUnloadFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_entry', models.DateTimeField(verbose_name='Время въезда')),
                ('datetime_exit', models.DateTimeField(verbose_name='Время выезда')),
                ('is_unloaded', models.BooleanField(verbose_name='Отгружено')),
                ('value', models.CharField(max_length=500, verbose_name='Объем контейнера')),
                ('container_type', models.CharField(max_length=500, verbose_name='Тип контейнера')),
                ('directory', models.CharField(max_length=500, verbose_name='Муниципальное образование')),
                ('count', models.IntegerField(verbose_name='Количество отгрузок')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nav_client.Device', verbose_name='Транспорт')),
                ('geozone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nav_client.GeoZone', verbose_name='Платформа')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='Отчет')),
                ('track_points', models.ManyToManyField(to='nav_client.Point', verbose_name='Точки маршрута')),
            ],
            options={
                'verbose_name': 'Факт отгрузки',
                'verbose_name_plural': 'Факты отгрузки',
            },
        ),
    ]
