# Generated by Django 2.2.9 on 2020-01-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav_client', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerunloadfact',
            name='device',
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default='1999-10-10', verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nav_client.Device', verbose_name='Транспорт'),
        ),
    ]
