# Generated by Django 2.2.10 on 2020-02-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200123_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerunloadfact',
            name='track_points',
            field=models.ManyToManyField(to='nav_client.FlatTableRow', verbose_name='Точки маршрута'),
        ),
    ]
