# Generated by Django 2.2.10 on 2020-03-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200225_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerunloadfact',
            name='datetime_entry',
            field=models.DateTimeField(null=True, verbose_name='Время въезда'),
        ),
        migrations.AlterField(
            model_name='containerunloadfact',
            name='datetime_exit',
            field=models.DateTimeField(null=True, verbose_name='Время выезда'),
        ),
    ]
