# Generated by Django 2.2.10 on 2020-03-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200304_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerunloadfact',
            name='nav_mt_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код площадки в МТ'),
        ),
    ]
