# Generated by Django 2.2.11 on 2020-03-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200304_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50, verbose_name='Материал контейнера')),
                ('volume', models.CharField(max_length=7, verbose_name='Объем контейнера')),
            ],
            options={
                'verbose_name': 'Тип контейнера',
                'verbose_name_plural': 'Типы контейнеров',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование оранизации')),
                ('details', models.CharField(max_length=500, verbose_name='Реквизиты организации')),
                ('contacts', models.CharField(max_length=250, verbose_name='Контактные данные')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
