# Generated by Django 2.2.10 on 2020-03-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_containerunloadfact_nav_mt_id'),
        ('reports', '0005_auto_20200310_1619'),
    ]

    operations = [
    ]
