# Generated by Django 2.2.11 on 2020-03-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_merge_20200313_1307'),
        ('reports', '0005_containertype_organization'),
    ]

    operations = [
    ]
