# Generated by Django 2.2.11 on 2020-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_merge_20200316_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='upload_time',
            field=models.IntegerField(default=30, verbose_name='Время на отгрузку в секундах'),
        ),
    ]
