# Generated by Django 2.2.11 on 2020-03-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20200326_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containertype',
            old_name='material',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='containertype',
            name='name',
            field=models.CharField(db_column='material', max_length=50, verbose_name='Название'),
        ),
    ]
