# Generated by Django 2.2.11 on 2020-03-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20200326_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
